# Site settings
title: How Urban Disease
email: 503262997@qq.com
description: > # this means to ignore newlines until "baseurl:"
  城市病成为现代不可忽略的问题
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: Yangxihao
email: 503262997@qq.com
#facebook_username: 
#twitter_username:
github_username: Xiaohuobanhahaha
#address:
#  - line:
#  - line:
  # Feel free to add more lines here 
#telephone:
copyright: 2019,Xiaohuobanhahaha Company.Inc

# API settings
#google_api_key:

# Build settings
markdown: kramdown