# Site settings
# in the templates available like {{ site.myvariable }}.
title: How Urban Disease Impact
email: 503262997@qq.com
brand: Yang Xihao
headline: City, Disease and Future
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://example.com" # the base hostname & protocol for your site
copyright: 2019 Whatever Company, Inc. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: 503262997@qq.com
#phone: +1-800-555-2016

# Tracking
#googleAnalitycsID: UA-83933844-1

